spring:
  application:
    name: admin-server
  security:
    user:
      name: "admin"
      password: "123"
  mail:
    host: smtp.qq.com
    username: xxx@qq.com
    password: xxx
    properties:
      mail.debug: false
      mail.smtp.auth: true
  boot:
    admin:
      notify:
        mail:
          from: xxx@qq.com
          to: xxx@qq.com
#          ignore-changes: UNKNOWN:UP
          ignore-changes:
            - "*:UP" # 从任何状态到up状态都不要发邮件通知
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
  
#  boot:
#    admin:
#      ui:
#        cache:
#          no-cache: true
#        cache-templates: false
server:
  port: 10012

eureka:
  instance:
#    metadata-map:
#      user:
#        name: "admin"
#        password: "123"
    lease-renewalIntervalInSeconds: 10  # client发送心跳给server端的频率，默认30秒
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5 # 读取服务注册信息频率，默认为30秒
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8891}/eureka/
      
management:
  endpoints:
    web:
#      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS