spring:
  application:
    name: admin-server

server:
  port: 10012

eureka:
#  instance:
#    lease-renewal-interval-in-seconds: 15000  # client发送心跳给server端的频率，默认30秒
  client:
#    registry-fetch-interval-seconds: 5000 # 读取服务注册信息频率，默认为30秒
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8891}/eureka/
      
management.security.enabled: false